import { IAnswer, IQuiz } from 'types/quiz';
import { ISpaceMember } from 'types/space';

export const MULTI_QUIZZES: IQuiz[] = [
  {
    quizId: 200,
    spaceId: 1,
    childId: 400,
    question: 'QuizBox 서비스 개발자의 Github ID는 무엇인가요?',
    isRoot: true,
    type: 'multi',
    answerResponses: [
      {
        answer: 'solchan',
        answerId: 1,
        isCorrect: false,
        quizId: 200,
      },
      {
        answer: 'solchan98',
        answerId: 2,
        isCorrect: true,
        quizId: 200,
      },
      {
        answer: 'solchan12',
        answerId: 3,
        isCorrect: false,
        quizId: 200,
      },
      {
        answer: 'solchan123',
        answerId: 4,
        isCorrect: false,
        quizId: 200,
      },
    ] as IAnswer[],
    hint: '',
    createdAt: '2023-01-14T14:29:43.70871',
    spaceMemberResponse: {
      email: 'sol@sol.com',
      joinedAt: '2023-01-14T14:28:25.299336',
      nickname: 'sol',
      role: 'ADMIN',
      spaceMemberId: 1,
    } as ISpaceMember,
  },
  {
    quizId: 201,
    spaceId: 1,
    childId: 399,
    question: '서버 개발 프레임워크가 아닌 것은 무엇인가요?',
    isRoot: true,
    type: 'multi',
    answerResponses: [
      {
        answer: 'SpringBoot',
        answerId: 11,
        isCorrect: false,
        quizId: 201,
      },
      {
        answer: 'React',
        answerId: 12,
        isCorrect: true,
        quizId: 201,
      },
      {
        answer: 'NestJS',
        answerId: 13,
        isCorrect: false,
        quizId: 201,
      },
      {
        answer: 'FastAPI',
        answerId: 14,
        isCorrect: false,
        quizId: 201,
      },
    ] as IAnswer[],
    hint: '',
    createdAt: '2023-01-14T14:29:43.70871',
    spaceMemberResponse: {
      email: 'sol@sol.com',
      joinedAt: '2023-01-14T14:28:25.299336',
      nickname: 'sol',
      role: 'ADMIN',
      spaceMemberId: 1,
    } as ISpaceMember,
  },
  {
    quizId: 201,
    spaceId: 1,
    childId: null,
    question: 'QuizBox는 어떤 클라우드 플랫폼을 사용하고 있을까요?',
    isRoot: true,
    type: 'multi',
    answerResponses: [
      {
        answer: 'AWS',
        answerId: 5,
        isCorrect: true,
        quizId: 201,
      },
      {
        answer: 'GCP',
        answerId: 6,
        isCorrect: false,
        quizId: 201,
      },
    ] as IAnswer[],
    hint: '',
    createdAt: '2023-01-14T14:29:43.70871',
    spaceMemberResponse: {
      email: 'sol@sol.com',
      joinedAt: '2023-01-14T14:28:25.299336',
      nickname: 'sol',
      role: 'ADMIN',
      spaceMemberId: 1,
    } as ISpaceMember,
  },
];

export const MULTI_CHILD_QUIZZES: IQuiz[] = [
  {
    quizId: 400,
    spaceId: 1,
    childId: null,
    question: '그렇다면 QuizBox 개발자의 이메일은 무엇일까요?',
    isRoot: false,
    type: 'multi',
    answerResponses: [
      {
        answer: 'thfcks@gmail.com',
        answerId: 8,
        isCorrect: false,
        quizId: 400,
      },
      {
        answer: 'dev.sol0427@gmail.com',
        answerId: 9,
        isCorrect: true,
        quizId: 400,
      },
      {
        answer: 'hello@world.com',
        answerId: 10,
        isCorrect: false,
        quizId: 400,
      },
    ] as IAnswer[],
    hint: '',
    createdAt: '2023-01-14T14:29:43.70871',
    spaceMemberResponse: {
      email: 'sol@sol.com',
      joinedAt: '2023-01-14T14:28:25.299336',
      nickname: 'sol',
      role: 'ADMIN',
      spaceMemberId: 1,
    } as ISpaceMember,
  },
  {
    quizId: 399,
    spaceId: 1,
    childId: null,
    question: '그렇다면 반대로 프론트 개발 프레임워크/ 라이브러리가 아닌 것은 무엇인가요?',
    isRoot: false,
    type: 'multi',
    answerResponses: [
      {
        answer: 'React',
        answerId: 8,
        isCorrect: false,
        quizId: 399,
      },
      {
        answer: 'SpringBoot',
        answerId: 9,
        isCorrect: true,
        quizId: 399,
      },
      {
        answer: 'Vue',
        answerId: 10,
        isCorrect: false,
        quizId: 399,
      },
      {
        answer: 'Django',
        answerId: 11,
        isCorrect: true,
        quizId: 399,
      },
    ] as IAnswer[],
    hint: '',
    createdAt: '2023-01-14T14:29:43.70871',
    spaceMemberResponse: {
      email: 'sol@sol.com',
      joinedAt: '2023-01-14T14:28:25.299336',
      nickname: 'sol',
      role: 'ADMIN',
      spaceMemberId: 1,
    } as ISpaceMember,
  },
];

export const FORM_QUIZZES: IQuiz[] = [
  {
    quizId: 99,
    spaceId: 1,
    childId: 100,
    question: '가장 최근에 읽은 개발 도서가 있나요?',
    isRoot: true,
    type: 'form',
    answerResponses: [
      {
        answer: 'EX) 이펙티브 자바 도서를 읽었습니다.',
        answerId: 99,
        isCorrect: true,
        quizId: 99,
      },
    ] as IAnswer[],
    hint: '',
    createdAt: '2023-01-14T14:29:43.70871',
    spaceMemberResponse: {
      email: 'sol@sol.com',
      joinedAt: '2023-01-14T14:28:25.299336',
      nickname: 'sol',
      role: 'ADMIN',
      spaceMemberId: 1,
    } as ISpaceMember,
  },
  {
    quizId: 98,
    spaceId: 1,
    childId: 102,
    question: '프로세스란 무엇인가요?',
    isRoot: true,
    type: 'form',
    answerResponses: [
      {
        answer:
          '프로세스란 메모리에 프로그램이 로드되어 PCB를 할당받아 프로세서에 할당되어 실행 가능한 프로그램을 뜻합니다.',
        answerId: 114,
        isCorrect: true,
        quizId: 98,
      },
    ] as IAnswer[],
    hint: '',
    createdAt: '2023-01-14T14:29:43.70871',
    spaceMemberResponse: {
      email: 'sol@sol.com',
      joinedAt: '2023-01-14T14:28:25.299336',
      nickname: 'sol',
      role: 'ADMIN',
      spaceMemberId: 1,
    } as ISpaceMember,
  },
  {
    quizId: 97,
    spaceId: 1,
    childId: null,
    question: '당신의 이름은 무엇인가요?',
    isRoot: true,
    type: 'form',
    answerResponses: [
      {
        answer: '본인 이름',
        answerId: 113,
        isCorrect: true,
        quizId: 97,
      },
    ] as IAnswer[],
    hint: '',
    createdAt: '2023-01-14T14:29:43.70871',
    spaceMemberResponse: {
      email: 'sol@sol.com',
      joinedAt: '2023-01-14T14:28:25.299336',
      nickname: 'sol',
      role: 'ADMIN',
      spaceMemberId: 1,
    } as ISpaceMember,
  },
  {
    quizId: 96,
    spaceId: 1,
    childId: 104,
    question: 'OSI 7 Layer에 대하여 설명해주세요.',
    isRoot: true,
    type: 'form',
    answerResponses: [
      {
        answer: '에프세트네데피',
        answerId: 115,
        isCorrect: true,
        quizId: 96,
      },
    ] as IAnswer[],
    hint: '',
    createdAt: '2023-01-14T14:29:43.70871',
    spaceMemberResponse: {
      email: 'sol@sol.com',
      joinedAt: '2023-01-14T14:28:25.299336',
      nickname: 'sol',
      role: 'ADMIN',
      spaceMemberId: 1,
    } as ISpaceMember,
  },
];

export const FORM_CHILD_QUIZ = [
  {
    quizId: 100,
    spaceId: 1,
    childId: 101,
    question: '그 책에서 어떤 부분이 가장 기억에 남나요?',
    isRoot: false,
    type: 'form',
    answerResponses: [
      {
        answer: '추상 클래스와 인터페이스에 대한 부분입니다.',
        answerId: 98,
        isCorrect: true,
        quizId: 100,
      },
    ] as IAnswer[],
    hint: '',
    createdAt: '2023-01-14T14:29:43.70871',
    spaceMemberResponse: {
      email: 'sol@sol.com',
      joinedAt: '2023-01-14T14:28:25.299336',
      nickname: 'sol',
      role: 'ADMIN',
      spaceMemberId: 1,
    } as ISpaceMember,
  },
  {
    quizId: 101,
    spaceId: 1,
    childId: null,
    question: '왜 그 부분이 가장 기억에 남나요?',
    isRoot: false,
    type: 'form',
    answerResponses: [
      {
        answer: '재밌었어용',
        answerId: 98,
        isCorrect: true,
        quizId: 101,
      },
    ] as IAnswer[],
    hint: '',
    createdAt: '2023-01-14T14:29:43.70871',
    spaceMemberResponse: {
      email: 'sol@sol.com',
      joinedAt: '2023-01-14T14:28:25.299336',
      nickname: 'sol',
      role: 'ADMIN',
      spaceMemberId: 1,
    } as ISpaceMember,
  },
  {
    quizId: 102,
    spaceId: 1,
    childId: 103,
    question: '그렇다면 스레드는 무엇인가요?',
    isRoot: false,
    type: 'form',
    answerResponses: [
      {
        answer: '스레드는 하나의 실행 단위이며, 하나의 프로세스는 하나 이상의 스레드를 가지고 있습니다.',
        answerId: 97,
        isCorrect: true,
        quizId: 102,
      },
    ] as IAnswer[],
    hint: '',
    createdAt: '2023-01-14T14:29:43.70871',
    spaceMemberResponse: {
      email: 'sol@sol.com',
      joinedAt: '2023-01-14T14:28:25.299336',
      nickname: 'sol',
      role: 'ADMIN',
      spaceMemberId: 1,
    } as ISpaceMember,
  },
  {
    quizId: 103,
    spaceId: 1,
    childId: null,
    question: '프로세스와 스레드가 매우 비슷한 것 같은데 어떤 차이를 가지고 있나요?',
    isRoot: false,
    type: 'form',
    answerResponses: [
      {
        answer:
          '프로세스는 상호 간의 데이터 공유가 불가능합니다. 이에 반해 스레드는 같은 프로세스 내 스레드 간 데이터 공유가 가능합니다.',
        answerId: 96,
        isCorrect: true,
        quizId: 103,
      },
    ] as IAnswer[],
    hint: '',
    createdAt: '2023-01-14T14:29:43.70871',
    spaceMemberResponse: {
      email: 'sol@sol.com',
      joinedAt: '2023-01-14T14:28:25.299336',
      nickname: 'sol',
      role: 'ADMIN',
      spaceMemberId: 1,
    } as ISpaceMember,
  },
  {
    quizId: 104,
    spaceId: 1,
    childId: 105,
    question: 'Transport Layer의 TCP 프로토콜에 대하여 설명해주세요.',
    isRoot: false,
    type: 'form',
    answerResponses: [
      {
        answer: 'TCP 프로토콜은 흐름제어, 혼잡제어 등의 기능을 제공합니다.',
        answerId: 95,
        isCorrect: true,
        quizId: 104,
      },
    ] as IAnswer[],
    hint: '',
    createdAt: '2023-01-14T14:29:43.70871',
    spaceMemberResponse: {
      email: 'sol@sol.com',
      joinedAt: '2023-01-14T14:28:25.299336',
      nickname: 'sol',
      role: 'ADMIN',
      spaceMemberId: 1,
    } as ISpaceMember,
  },
  {
    quizId: 105,
    spaceId: 1,
    childId: null,
    question: 'Transport Layer의 UDP 프로토콜에 대하여 설명해주세요.',
    isRoot: false,
    type: 'form',
    answerResponses: [
      {
        answer:
          'UDP 프로토콜은 TCP와 다르게 패킷 전송 중 오류가 발생하여도 이에 대한 후처리를 진행하지 않습니다. 대신 속도가 빠릅니다.',
        answerId: 94,
        isCorrect: true,
        quizId: 105,
      },
    ] as IAnswer[],
    hint: '',
    createdAt: '2023-01-14T14:29:43.70871',
    spaceMemberResponse: {
      email: 'sol@sol.com',
      joinedAt: '2023-01-14T14:28:25.299336',
      nickname: 'sol',
      role: 'ADMIN',
      spaceMemberId: 1,
    } as ISpaceMember,
  },
];
