name: Build And Deploy

on:
  push:
    branches:
      - 'feature/**' # Test, 나중에 develop로 변경

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build
        run: |
          npm install
          npm run build

      - name: Authenticate with Google Cloud
        id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
            credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: 'Upload to Bucket'
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
            path: '/build'
            destination: ${{ secrets.GCP_BUCKET_NAME }}

      - name: Connect GCE And Execute Deploy Script
        id: 'compute-ssh'
        uses: 'google-github-actions/ssh-compute@v0'
        with:
            instance_name: 'dev'
            zone: 'asia-northeast3-a'
            ssh_private_key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
            script: "./deploy.sh"