name: Build And Deploy

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup Properties
        run: echo "${{ secrets.ENV }}" > .env

      - name: Build
        run: |
          npm install -force
          CI="" npm run build
          tar -cvf build.tar build

      - name: Deploy
        uses: nogsantos/scp-deploy@master
        with:
          src: build.tar
          host: ${{ secrets.SERVER_HOST }}
          remote: ${{ secrets.SERVER_FILE_PATH }}
          port: 22
          user: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}

      - name: SSH Compute
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: sh frontend-deploy.sh
